model: unet
lossfn: MSE
gapsize: 0.1
gaptype: 'default'
perm: A
casename: ''
epochs: 600
lr: 0.001
step: 100
ckpt_freq: 900
workers: 4
batchsize: 64
target_imgshape: [128, 128]
outputpath: ./outputs/
filepath: ./data/LSP_r1300_p40_small.h5